
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'MapGallery User Manual'
theme = 'docdock'

[params]
themeStyle = 'flex'
themeVariant = 'blue'
[outputs]
home = [ "HTML", "RSS", "JSON"]